# Generated by Django 3.1.7 on 2021-03-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210317_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bid',
            new_name='bid_entry',
        ),
    ]
